# 1.Setting up the master folder

In [11]:
from pathlib import Path 
#Path represents file system paths as objects, so you can use / to join paths, .iterdir() to list contents, .is_dir() to check types, and so on.

import json 
#reads and writes JSON files

master_folder = Path(r"O:\archive\projects\2020_euSNN\Neuropixels_RT_mPFC\data\2_processed")

# 2. Finding valid sessions and building a summary table

In [18]:

#find folders that contain a share folder and a session_info.json file within it


folders_with_share = [] 
#Creates an empty list. It will collect the session folders that pass the check.


for folder in master_folder.iterdir():
#Loops over every item in the master folder, one at a time, storing each in folder.

    if not folder.is_dir():
        continue
    share_folder = folder / "share"
    session_info_file = share_folder / "session_info.json"
    if share_folder.is_dir() and session_info_file.is_file():
        folders_with_share.append(folder)
i = 0

for folder in folders_with_share:

    current_folder = folders_with_share[i] / Path(r"share\session_info.json")
    i += 1
    with open(current_folder, 'r') as f:
        session_info = json.load(f)

    import pandas as pd

rows = []

for folder in folders_with_share:
    session_info_file = folder / "share" / "session_info.json"

    with open(session_info_file, "r") as f:
        session_info = json.load(f)

    rows.append({
        "session_id": session_info["session_id"],
        "duration_min": session_info["ephys"]["duration_s"] / 60,
        "n_trials": session_info["behaviour"]["n_trials"],
        "n_correct": session_info["behaviour"]["n_correct"],
        "n_early": session_info["behaviour"]["n_early"],
        "n_late": session_info["behaviour"]["n_late"],
        "n_samples": session_info["ephys"]["n_samples"],
    })

Sessions_info = pd.DataFrame(rows)

Sessions_info

,session_id,duration_min,n_trials,n_correct,n_early,n_late,n_samples
0,20260510_r0000135_wt_1625,53.835616,143,14,128,1,96904109
1,20260510_r0000136_wt_1926,35.082763,170,87,50,32,63148974
2,20260511_r0000136_wt_0909,8.074871,42,26,8,6,14534768
3,20260511_r0000136_wt_0930,21.356627,86,46,20,18,38441929
4,20260511_r0000136_wt_1832,29.290998,121,56,20,41,52723796
...,...,...,...,...,...,...,...
58,20260623_r0000135_wt_1111,23.513238,133,86,39,8,42323829
59,20260624_r0000134_wt_1323,19.327171,102,74,10,18,34788907
60,20260624_r0000135_wt_1257,22.306118,140,66,74,0,40151012
61,20260625_r0000134_wt_1820,17.865802,86,58,23,4,32158443
62,20260625_r0000135_wt_1846,19.862663,131,73,54,4,35752794

# 3. Loading the trial data of one session

In [4]:
Trials_Summary_for_one_session = pd.read_csv(r"O:\archive\projects\2020_euSNN\Neuropixels_RT_mPFC\data\2_processed\20260513_r0000136_wt_1729\share\trials.csv")
Trials_Summary_for_one_session

,session_id,trial_index,press,full_hold,release,tone,vibration,tone_duration,tone_frequency,trial_end,...,prev_correct,release_type,anticipatory,running_error_rate,press_np_s,go_signal_np_s,release_np_s,reward_np_s,trial_end_np_s,press_ttl_np_s
0,20260513_r0000136_wt_1729,0,54.56,55.58,64.17,55.61,0.0,0.2,8000.0,56.12,...,NaN,late,0,NaN,NaN,62.475316,71.035289,NaN,62.985314,61.425933
1,20260513_r0000136_wt_1729,1,78.62,79.64,79.92,79.67,0.0,0.2,8000.0,79.92,...,0.0,reactive,0,0.00,85.485244,86.535241,86.785240,86.825240,86.785240,85.486500
2,20260513_r0000136_wt_1729,2,104.72,105.74,106.95,105.77,0.0,0.2,8000.0,106.28,...,1.0,late,0,0.00,111.585166,112.635165,113.815163,NaN,113.145164,111.583267
3,20260513_r0000136_wt_1729,3,116.02,0.00,116.24,0.00,0.0,0.0,0.0,116.24,...,0.0,early,0,0.00,122.885152,NaN,123.105151,NaN,123.105151,NaN
4,20260513_r0000136_wt_1729,4,139.61,0.00,139.80,0.00,0.0,0.0,0.0,139.80,...,0.0,early,0,0.25,146.475077,NaN,146.665075,NaN,146.665075,146.471267
5,20260513_r0000136_wt_1729,5,148.60,148.92,149.30,148.95,0.0,0.2,8000.0,149.30,...,0.0,reactive,0,0.40,155.465079,155.815078,156.165077,156.205077,156.165077,155.458467
6,20260513_r0000136_wt_1729,6,167.73,0.00,168.43,0.00,0.0,0.0,0.0,168.43,...,1.0,early,0,0.40,174.595015,NaN,175.295013,NaN,175.295013,174.595733
7,20260513_r0000136_wt_1729,7,174.88,175.90,176.54,175.93,0.0,0.2,8000.0,176.44,...,0.0,late,0,0.60,181.745001,182.794999,183.404998,NaN,183.304998,181.742667
8,20260513_r0000136_wt_1729,8,181.24,181.56,182.46,181.59,0.0,0.2,8000.0,182.10,...,0.0,late,0,0.60,188.104988,188.454988,189.324985,NaN,188.964986,188.099400
9,20260513_r0000136_wt_1729,9,202.71,203.73,207.02,203.76,0.0,0.2,8000.0,204.27,...,0.0,late,0,0.40,209.574930,210.624927,213.884920,NaN,211.134926,209.570000
10,20260513_r0000136_wt_1729,10,211.68,212.00,212.37,212.03,0.0,0.2,8000.0,212.37,...,0.0,reactive,0,0.20,218.544909,218.894907,219.234906,219.274906,219.234906,218.542267
11,20260513_r0000136_wt_1729,11,226.66,226.98,227.73,227.01,0.0,0.2,8000.0,227.52,...,1.0,late,0,0.20,233.524848,233.874848,234.594848,NaN,234.384848,233.521933
12,20260513_r0000136_wt_1729,12,233.61,234.63,235.75,234.66,0.0,0.2,8000.0,235.17,...,0.0,late,0,0.00,240.474845,241.524844,242.614843,NaN,242.034844,240.467600
13,20260513_r0000136_wt_1729,13,242.92,0.00,243.29,0.00,0.0,0.0,0.0,243.29,...,0.0,early,0,0.00,249.784837,NaN,250.154835,NaN,250.154835,249.780667
14,20260513_r0000136_wt_1729,14,254.79,255.81,256.11,255.84,0.0,0.2,8000.0,256.11,...,0.0,reactive,0,0.20,261.654800,262.704796,262.974795,263.014795,262.974795,261.654933
15,20260513_r0000136_wt_1729,15,271.15,271.47,272.70,271.50,0.0,0.2,8000.0,272.01,...,1.0,late,0,0.20,278.014749,278.364749,279.564750,NaN,278.874749,278.013733
16,20260513_r0000136_wt_1729,16,280.02,281.04,281.37,281.07,0.0,0.2,8000.0,281.37,...,0.0,reactive,0,0.20,286.884752,287.934748,288.234747,288.274747,288.234747,286.876333
17,20260513_r0000136_wt_1729,17,293.11,294.13,294.30,294.16,0.0,0.2,8000.0,294.30,...,1.0,reactive,0,0.20,299.974702,301.024700,301.164700,301.204700,301.164700,299.969967
18,20260513_r0000136_wt_1729,18,307.40,307.72,308.15,307.75,0.0,0.2,8000.0,308.15,...,1.0,reactive,0,0.20,314.264674,314.614673,315.014673,315.054673,315.014673,314.262767
19,20260513_r0000136_wt_1729,19,319.39,319.71,320.24,319.74,0.0,0.2,8000.0,320.24,...,1.0,reactive,0,0.00,326.254658,326.604656,327.104655,327.144655,327.104655,326.254200
20,20260513_r0000136_wt_1729,20,333.09,334.11,334.44,334.14,0.0,0.2,8000.0,334.44,...,1.0,reactive,0,0.00,339.954610,341.004610,341.304609,341.344609,341.304609,339.952733
21,20260513_r0000136_wt_1729,21,353.59,353.91,354.21,353.94,0.0,0.2,8000.0,354.21,...,1.0,reactive,0,0.00,360.454594,360.804593,361.074592,361.114592,361.074592,360.451067
22,20260513_r0000136_wt_1729,22,362.73,363.05,363.64,363.08,0.0,0.2,8000.0,363.59,...,1.0,late,0,0.00,369.594575,369.944574,370.504572,NaN,370.454572,369.591600
23,20260513_r0000136_wt_1729,23,369.08,0.00,369.44,0.00,0.0,0.0,0.0,369.44,...,0.0,early,0,0.00,375.944549,NaN,376.304547,NaN,376.304547,375.939800
24,20260513_r0000136_wt_1729,24,373.29,374.31,374.84,374.34,0.0,0.2,8000.0,374.84,...,0.0,reactive,0,0.20,380.154527,381.204524,381.704522,381.744522,381.704522,380.148500
25,20260513_r0000136_wt_1729,25,394.66,394.98,395.34,395.01,0.0,0.2,8000.0,395.34,...,1.0,reactive,0,0.20,401.524466,401.874465,402.204465,402.244465,402.204465,401.513667
26,20260513_r0000136_wt_1729,26,404.09,405.11,405.40,405.14,0.0,0.2,8000.0,405.40,...,1.0,reactive,0,0.20,410.954450,412.004448,412.264447,412.304447,412.264447,410.947067
27,20260513_r0000136_wt_1729,27,414.07,0.00,414.17,0.00,0.0,0.0,0.0,414.17,...,1.0,early,0,0.20,420.934427,NaN,421.034427,NaN,421.034427,NaN
28,20260513_r0000136_wt_1729,28,419.38,419.70,420.13,419.73,0.0,0.2,8000.0,420.13,...,0.0,reactive,0,0.40,426.244415,426.594414,426.994414,427.034414,426.994414,426.233467
29,20260513_r0000136_wt_1729,29,428.17,428.49,428.81,428.52,0.0,0.2,8000.0,428.81,...,1.0,reactive,0,0.20,435.034412,435.384411,435.674410,435.714410,435.674410,435.030033
30,20260513_r0000136_wt_1729,30,439.04,439.36,440.36,439.39,0.0,0.2,8000.0,439.90,...,1.0,late,0,0.20,445.904388,446.254386,447.224381,NaN,446.764384,445.893667
31,20260513_r0000136_wt_1729,31,444.97,0.00,445.19,0.00,0.0,0.0,0.0,445.19,...,0.0,early,0,0.20,451.834359,NaN,452.054357,NaN,452.054357,451.824400
32,20260513_r0000136_wt_1729,32,452.36,0.00,452.60,0.00,0.0,0.0,0.0,452.60,...,0.0,early,0,0.40,459.224366,NaN,459.464358,NaN,459.464358,459.213100
33,20260513_r0000136_wt_1729,33,457.90,458.92,459.26,458.95,0.0,0.2,8000.0,459.26,...,0.0,reactive,0,0.40,464.764325,465.814322,466.124322,466.164322,466.124322,464.761500
34,20260513_r0000136_wt_1729,34,473.27,474.29,474.75,474.32,0.0,0.2,8000.0,474.75,...,1.0,reactive,0,0.40,480.134289,481.184287,481.614286,481.654286,481.614286,480.130967
35,20260513_r0000136_wt_1729,35,492.51,493.53,493.88,493.56,0.0,0.2,8000.0,493.88,...,1.0,reactive,0,0.40,499.374253,500.424251,500.744250,500.784250,500.744250,499.369433
36,20260513_r0000136_wt_1729,36,504.12,505.14,505.23,505.17,0.0,0.2,8000.0,505.23,...,1.0,anticipatory,1,0.40,510.984226,512.034223,512.094223,512.134223,512.094223,510.979600
37,20260513_r0000136_wt_1729,37,522.95,523.97,525.05,524.00,0.0,0.2,8000.0,524.51,...,1.0,late,0,0.20,529.814172,530.864168,531.914165,NaN,531.374167,529.811233
38,20260513_r0000136_wt_1729,38,541.20,0.00,542.21,0.00,0.0,0.0,0.0,542.21,...,0.0,early,0,0.00,NaN,NaN,NaN,NaN,NaN,548.060333